
POST http://localhost:3000/auth/send-otp
Content-Type: application/json

{
     
    "phoneNumber":"9588500964"

}




###
POST http://localhost:3000/auth/authenticate
Content-Type: application/json

{ 
      // owner phone number 
     // "phoneNumber":"9588500964",
     // maintianer 01
      "phoneNumber":"7412589630",
    // maintainer 02
    //"phoneNumber":"1593578520",
     // tenant phone number 
    // "phoneNumber":"8814058881",
      "code":"604143"
}


###
PUT http://localhost:3000/auth/forgot-password
Content-Type: application/json

{
     "email":"jack@cas.com"
}


###
POST http://localhost:3000/auth/reset-password
Content-Type: application/json

{
      "newPassword":"dfddff",
      "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGI5MDMzZWQwMzVhNTI3YmM3YzhiN2YiLCJuYW1lIjoiamFjayIsImVtYWlsIjoiamFja0BjYXMuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkT1RuQlJXT2xwMG9iYkZjOUVpd1FmdWdlNjRjeVJMS0k0aHRpeG5NS2NtZ0xXNktNbkJjN0siLCJwaG9uZU51bWJlciI6Ijk1ODg1MDA5NjQiLCJpc093bmVyIjoiT3duZXIiLCJyZXNldExpbmsiOiIiLCJpYXQiOjE2MjI3Mzg4MTcsImV4cCI6MTYyMjc0MDAxNywiaXNzIjoicmVudGVlLmNvbSJ9.KDFqBF1lRrp66Wt84L4NCvYTDLp9hO6UI8U4MPxK1wc"
      
}



###
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTBmODYwYzA0Njc5YTI1ZjgzYjNmYzciLCJwaG9uZU51bWJlciI6Ijc0MTI1ODk2MzAiLCJpc093bmVyIjoiT3duZXIiLCJpYXQiOjE2Mjg0MDczMDksImV4cCI6MTYyODQwNzkwOSwiaXNzIjoicmVudGVlLmNvbSJ9.yZI_xs3mJFsk6Yu2BIzeJkNrbBSKrn063WNkKh-sj8M"
}